(function(){
'use strict';
const T=window.Tenant,M=window.TenantMaps,$=q=>document.querySelector(q);
const SAVE='tenant-floorplan-v3',META='tenant-collection-v3';
let storageOK=true,state=T.initial(),collection={achievements:[],endings:[]},loaded=false;
try{const a=JSON.parse(localStorage.getItem(SAVE)||'null');if(a&&a.version===3&&M.MAPS[a.floor]&&Number.isFinite(a.time)&&Array.isArray(a.clues)){state=Object.assign(T.initial(),a);loaded=true;}const c=JSON.parse(localStorage.getItem(META)||'null');if(c&&Array.isArray(c.achievements)&&Array.isArray(c.endings))collection=c;}catch{storageOK=false;}
if(!M.canStand(state.floor,state.x,state.y))[state.x,state.y]=M.MAPS[state.floor].spawn;
let muted=false,ctxAudio=null,master=null,keys=new Set(),active=null,effects=[],last=0,step=0,moving=false,toastTimer,saveTimer=0,dialogMode='',audioEvents=0,animations=0;
const canvas=$('#map'),ctx=canvas.getContext('2d'),viewport=$('#viewport'),overlay=$('#overlay');
const escape=text=>String(text).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function stamp(t){const m=t%1440;return String(Math.floor(m/60)).padStart(2,'0')+':'+String(m%60).padStart(2,'0');}
function unlockAudio(){if(!ctxAudio){try{ctxAudio=new(window.AudioContext||window.webkitAudioContext)();master=ctxAudio.createGain();master.gain.value=muted?0:.15;master.connect(ctxAudio.destination);}catch{return;}}if(ctxAudio.state==='suspended')ctxAudio.resume().catch(()=>{});}
function tone(freq,at,duration,type='sine',to){if(!ctxAudio)return;const o=ctxAudio.createOscillator(),g=ctxAudio.createGain();o.type=type;o.frequency.setValueAtTime(freq,at);if(to)o.frequency.exponentialRampToValueAtTime(to,at+duration);g.gain.setValueAtTime(.001,at);g.gain.exponentialRampToValueAtTime(.3,at+.012);g.gain.exponentialRampToValueAtTime(.001,at+duration);o.connect(g);g.connect(master);o.start(at);o.stop(at+duration+.02);o.onended=()=>{o.disconnect();g.disconnect();};}
function sound(type='paper'){unlockAudio();if(!ctxAudio)return;audioEvents++;const t=ctxAudio.currentTime;
 const sounds={paper:[[700,.08,450]],door:[[120,.25,55],[180,.18,80]],water:[[380,.13,1100],[780,.15,320],[460,.12,900]],cloth:[[240,.15,530],[510,.15,220]],clock:[[850,.05,750],[630,.05,530]],magic:[[330,.25,660],[495,.25,990],[660,.3,1320]],danger:[[110,.3,52],[97,.25,43]],rest:[[220,.4,330],[330,.4,440]],ending:[[262,.35,262],[330,.35,330],[392,.35,392],[523,.6,523]],cat:[[640,.22,1050],[1050,.3,480]],step:[[85,.055,45]],knock:[[150,.075,70],[150,.075,70],[110,.15,55]]};
 (sounds[type]||sounds.paper).forEach((n,i)=>tone(n[0],t+i*(type==='knock'?.22:.09),n[1],type==='danger'?'sawtooth':'sine',n[2]));}
function animate(el,name){el.classList.remove(name);void el.offsetWidth;el.classList.add(name);animations++;}
function feedback(type='paper',object=active){sound(type);const o=object||{x:state.x-10,y:state.y-10,w:20,h:20};effects.push({floor:state.floor,x:o.x+o.w/2,y:o.y+o.h/2,life:1,type});animate(viewport,type==='danger'?'shake':'pulse');if(!overlay.hidden)animate($('#dialog'),'pulse');}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3500);}
function save(){try{localStorage.setItem(SAVE,JSON.stringify(state));localStorage.setItem(META,JSON.stringify(collection));storageOK=true;}catch{storageOK=false;}$('#saveStatus').textContent=storageOK?'已自动保存 · 本机':'浏览器未允许保存 · 本次仍可玩';}
function objective(){if(state.ending)return '本周目已结束。可查看结算与成就簿，或开始新周目。';if(!state.rulesRead)return '先到左下玄关的入户门，靠近后按 E 阅读须知。';if(!state.key)return '探索仓库储物柜，取得照片与钥匙；或整理现场走正常退租路线。';if(!state.diary)return '钥匙能打开卧室 3 与阁楼。读日记将打破禁令；也可以选择继续遵守规则。';if(!state.runes)return '带着日记和照片上阁楼，寻找墙上的原初法则。';if(!state.origin)return '回安全屋书桌，将照片、日记与原初法则关联。';return '选择命运：阁楼午夜仪式、镜后终端考核，或在安全屋同步反向规则。';}
function renderHUD(){const map=M.MAPS[state.floor];$('#floorCode').textContent=map.code;$('#floorName').textContent=map.name;$('#time').textContent=stamp(state.time);$('#day').textContent='第 '+T.day(state)+' 天';$('#phase').textContent=T.minute(state)<360?'深夜':T.minute(state)<1080?'白天':'傍晚';$('#anomaly').textContent=state.anomaly+'/8';$('#suspicion').textContent=state.suspicion+'/6';$('#anomalyMeter').value=state.anomaly;$('#suspicionMeter').value=state.suspicion;$('#objective').textContent=objective();$('#deadline').textContent=state.floor==='basement'&&!state.ending?'返程剩余 '+Math.max(0,state.basementDeadline-state.time)+' 分钟 · 楼梯需 2 分钟，3:33 前离开':'';
 const inventory=[];if(state.rulesRead)inventory.push(state.returned?'须知已归位':'入住须知');if(state.milkTaken)inventory.push('牛奶 '+state.milk+' 口');if(state.key)inventory.push('旧钥匙');if(state.photo)inventory.push('半张照片');if(state.flashlight)inventory.push('手电 '+state.battery+'/3');if(state.cleaner)inventory.push('蓝瓶与布');if(state.diary)inventory.push('房东日记');if(state.runes)inventory.push('原初法则');if(state.job)inventory.push('录用通知');$('#inventory').innerHTML=inventory.length?inventory.map(v=>'<span>'+escape(v)+'</span>').join(''):'<span>口袋里只有 204 室钥匙</span>';
 $('#log').innerHTML=state.logs.slice(0,30).map(l=>'<p><time>DAY '+(Math.floor(l.time/1440)+1)+' / '+stamp(l.time)+'</time>'+escape(l.text)+'</p>').join('');$('#progress').textContent=state.achievements.length+' 成就 · '+state.visited.length+'/4 区域';}
function openDialog(title,body,choices=[],eyebrow='INVESTIGATION',mode='info'){keys.clear();moving=false;dialogMode=mode;$('#dialogEyebrow').textContent=eyebrow;$('#dialogTitle').textContent=title;$('#dialogBody').innerHTML=body;$('#choices').replaceChildren();choices.forEach(c=>{const b=document.createElement('button');b.textContent=c.label;if(c.desc){const small=document.createElement('small');small.textContent=c.desc;b.appendChild(small);}b.disabled=c.enabled===false;if(c.danger)b.classList.add('danger');if(c.key)b.dataset.key=c.key;b.onclick=c.run;$('#choices').appendChild(b);});$('#closeDialog').hidden=mode==='ending';overlay.hidden=false;animate($('#dialog'),'pulse');$('#dialog').scrollTop=0;$('#closeDialog').focus();if(mode==='ending')$('#choices button')?.focus();}
function closeDialog(){if(state.ending&&dialogMode==='ending')return;feedback('paper');overlay.hidden=true;keys.clear();dialogMode='';canvas.focus();}
function showObject(o){active=o;const choices=T.options(state,o.id).map(op=>({...op,danger:['sign','imitate','openDoor','hopWrong','stare'].includes(op.key),run:()=>perform(o,op.key)}));openDialog(o.name,'<p>'+escape(T.describe(state,o.id))+'</p><p class="muted">阅读与移动不消耗时间。操作默认耗时 2 分钟，等待与休息另行注明。</p>',choices,'OBJECT / '+o.id.toUpperCase(),'object');}
function perform(o,key){const floorBefore=state.floor;const result=T.execute(state,o.id,key);feedback(result.sound||'paper',o);state.achievements.forEach(id=>{if(!collection.achievements.includes(id))collection.achievements.push(id);});if(result.earned?.length){toast('成就解锁 · '+result.earned.map(id=>T.ACHIEVEMENTS[id][0]).join(' / '));sound('magic');}
 if(floorBefore!==state.floor){active=null;overlay.hidden=true;animate($('#floorTransition'),'transition');canvas.focus();}
 renderHUD();save();if(state.ending){if(!collection.endings.includes(state.ending))collection.endings.push(state.ending);save();settlement();return;}
 if(floorBefore===state.floor){const lines=(result.text||'操作完成。').split('\n').map(v=>'<p>'+escape(v)+'</p>').join('');openDialog(o.name,lines,[{label:'继续查看',run:()=>{feedback('paper');showObject(o);}},{label:'返回地图',run:closeDialog}],'ACTION / '+stamp(state.time),'result');}
}
function interact(){if(!overlay.hidden||state.ending)return;active=M.nearby(state);if(!active){feedback('paper');toast('再靠近一点：物件会亮起边框与 E 提示。');return;}feedback(['door','window'].includes(active.id)?'knock':'paper',active);showObject(active);}
function journal(){feedback('paper');const rules=state.rulesRead?'<ol>'+T.RULES.map(x=>'<li>'+escape(x)+'</li>').join('')+'</ol>':'<p>先在入户门阅读守则。</p>';const evidenceNames={rules:'入住须知',milk:'瓶底标签',window:'敲窗声与光',reflection:'镜后入口',shoes:'鞋底反向纸条',photo:'204 照片',diary:'王秀兰的日记',runes:'原初法则',rug:'跳房子格线',archive:'地下室返程时限',contract:'虚假接替协议',terminal:'管理员责任',knock:'不同访客的节奏',plant:'第二口牛奶的反应'};const clues=state.clues.map(id=>'<div class="card"><b>'+escape(evidenceNames[id]||id)+'</b></div>').join('');openDialog('心理笔记',rules+'<h3>已发现的证据</h3><div class="cards">'+clues+'</div><h3>已验证的关联</h3><p>'+escape(state.origin?'房东创造规则以镇压实体，也被契约束缚。':state.hypotheses.includes('plant')?'第二次浇奶会使植物指向窗户。':'还没有完整推导。安全屋书桌可以关联证据。')+'</p><p class="muted">长线玩法保留 7 / 30 / 100 天门槛。床边可以在现场符合规则后，逐日模拟重复生活。每一条结局都有对应状态要求，异常无法抹除违规历史。</p>',[{label:'返回地图',run:()=>{if(state.ending)settlement();else closeDialog();}}],'JOURNAL','journal');}
function achievementCards(ids,all=false){return Object.entries(T.ACHIEVEMENTS).filter(([id])=>all||ids.includes(id)).map(([id,a])=>'<div class="card '+(ids.includes(id)?'earned':'')+'"><b>'+(ids.includes(id)?'✓ ':'○ ')+escape(a[0])+'</b><small>'+escape(a[1])+'</small></div>').join('');}
function showCollection(){feedback('paper');openDialog('成就与结局收藏','<p>本机累计 '+collection.achievements.length+' / '+Object.keys(T.ACHIEVEMENTS).length+' 成就；本周目 '+state.achievements.length+' 项。新周目会保留收藏。</p><div class="cards">'+achievementCards(collection.achievements,true)+'</div><h3>结局档案</h3><div class="cards">'+Object.entries(T.ENDINGS).map(([id,v])=>'<div class="card '+(collection.endings.includes(id)?'earned':'')+'"><b>'+escape(v[0])+'</b><small>'+(collection.endings.includes(id)?'已抵达':'尚未抵达')+'</small></div>').join('')+'</div>',[{label:state.ending?'返回结算':'返回地图',run:()=>state.ending?settlement():closeDialog()}],'COLLECTION','collection');}
function settlement(){const e=T.ENDINGS[state.ending];sound(['trapped','trap','lost'].includes(state.ending)?'danger':'ending');openDialog(e[0],'<div class="ending-hero"><small>'+escape(e[1])+'</small><p><b>'+escape(e[0])+'</b></p></div><p>'+escape(e[2])+'</p><div class="settlement"><div>住过的日子<b>'+T.day(state)+'</b></div><div>合规天数<b>'+state.cleanDays+'</b></div><div>探索区域<b>'+state.visited.length+'/4</b></div><div>互动次数<b>'+state.interactions+'</b></div><div>违规次数<b>'+state.violationsTotal+'</b></div><div>秘密通道<b>'+state.shortcuts.length+'/5</b></div></div><h3>本周目获得的成就 · '+state.achievements.length+'</h3><div class="cards">'+(achievementCards(state.achievements)||'<p>本周目尚未解锁成就。换一种路线，再试一次。</p>')+'</div>',[{label:'开始新周目 · 保留成就收藏',run:newRun},{label:'查看全部成就与结局',run:showCollection}],'LEASE CLOSED / 本周目结算','ending');}
function newRun(){feedback('door');state=T.initial();active=null;keys.clear();effects=[];overlay.hidden=true;renderHUD();save();animate($('#floorTransition'),'transition');canvas.focus();}
function confirmRestart(){feedback('paper');openDialog('开始新周目？','<p>当前探索进度会重置。已经解锁的成就和结局收藏将保留。</p>',[{label:'确认开始新周目',run:newRun},{label:'继续当前周目',run:()=>state.ending?settlement():closeDialog()}],'NEW LEASE','restart');}
function rect(x,y,w,h,fill,stroke){ctx.fillStyle=fill;ctx.fillRect(x,y,w,h);if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=1;ctx.strokeRect(x+.5,y+.5,w-1,h-1);}}
function line(x,y,x2,y2,color,width=1){ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x2,y2);ctx.strokeStyle=color;ctx.lineWidth=width;ctx.stroke();}
function circle(x,y,r,color,stroke){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fillStyle=color;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.stroke();}}
function text(str,x,y,color='#d4d1b4',size=12,align='center'){ctx.font=size+'px "Microsoft YaHei", sans-serif';ctx.textAlign=align;ctx.fillStyle=color;ctx.fillText(str,x,y);}
function drawObject(o,now,near){const {x,y,w,h,kind}=o;const highlight=near&&near.id===o.id;const fx=effects.find(f=>f.floor===state.floor&&Math.abs(f.x-(x+w/2))<2&&Math.abs(f.y-(y+h/2))<2);ctx.save();if(fx){ctx.translate(x+w/2,y+h/2);ctx.rotate(Math.sin(fx.life*22)*.025);ctx.translate(-x-w/2,-y-h/2);}ctx.shadowColor='#06110e66';ctx.shadowBlur=5;ctx.shadowOffsetY=4;
 const color=['stairs','mirror'].includes(kind)?'#597b7a':kind==='plant'?'#65835d':'#7a7958';rect(x,y,w,h,color,'#b1b392');ctx.shadowBlur=0;ctx.shadowOffsetY=0;
 switch(kind){
 case 'bed':rect(x+5,y+5,w-10,h-10,'#57776b','#99ab8e');rect(x+12,y+9,w-24,22,'#babd9c');line(x+8,y+39,x+w-8,y+39,'#90a58a',2);break;
 case 'stairs':for(let j=6;j<h-3;j+=8)line(x+5,y+j,x+w-5,y+j,'#c2cfb3');text(o.id==='up'?'↑':'↕',x+w/2,y+h/2+5,'#152e29',22);break;
 case 'fridge':rect(x+5,y+5,w-10,h-10,'#adb7a0','#dae0c6');line(x+5,y+h*.4,x+w-5,y+h*.4,'#526b5f',2);line(x+w-12,y+h*.58,x+w-12,y+h*.8,'#526b5f',3);break;
 case 'desk':rect(x+8,y+7,w*.44,h*.52,'#d4ceb0');line(x+12,y+14,x+w*.42,y+14,'#8f977a');rect(x+w*.6,y+8,w*.25,h*.48,'#344d3d','#9aaa85');break;
 case 'cabinet':line(x+w/2,y+4,x+w/2,y+h-4,'#c0bc91');circle(x+w/2-7,y+h/2,2,'#dcd0a5');circle(x+w/2+7,y+h/2,2,'#dcd0a5');break;
 case 'plant':rect(x,y,w,h,'#263e30','#667d60');circle(x+w/2,y+h/2,12,'#98775a');for(let i=0;i<6;i++){const a=i*Math.PI/3+(state.plantUntil>state.time?now*.001:0);ctx.save();ctx.translate(x+w/2,y+h/2);ctx.rotate(a);ctx.fillStyle=i%2?'#8fb580':'#638c6c';ctx.beginPath();ctx.ellipse(9,0,12,5,0,0,Math.PI*2);ctx.fill();ctx.restore();}break;
 case 'window':rect(x+4,y+4,w-8,h-8,state.windowOpen?'#142b2e':'#8da9a3');line(x+w/2,y+3,x+w/2,y+h-3,'#d5c5a0',3);if(!state.curtainOpen){rect(x+2,y+2,w*.4,h-4,'#926f5b');rect(x+w*.6,y+2,w*.38,h-4,'#926f5b');}break;
 case 'mirror':rect(x+5,y+4,w-10,h-8,state.mirrorClean||state.floor==='mirror'?'#a3ccc1':'#677b6d');line(x+9,y+h-8,x+w-10,y+7,'#c8d9c1');break;
 case 'shoes':rect(x,y,w,h,'#334c3d','#667960');ctx.save();ctx.translate(x+w/2,y+h/2);if(state.shoesIn)ctx.rotate(Math.PI);for(let j=-9;j<=9;j+=18){ctx.fillStyle='#c0b082';ctx.beginPath();ctx.ellipse(j,0,5,10,0,0,Math.PI*2);ctx.fill();line(j-3,-4,j+3,-4,'#5f674b',2);}ctx.restore();break;
 case 'clock':circle(x+w/2,y+h/2,w/2-3,'#d2c6a0','#8f987d');line(x+w/2,y+h/2,x+w/2,y+7,'#394b39',2);line(x+w/2,y+h/2,x+w-8,y+h/2,'#394b39',2);break;
 case 'tray':rect(x+4,y+4,w-8,h-8,'#b4b397');circle(x+w*.48,y+h*.48,11,'#dcd3b3','#6d806c');if(state.bottle)rect(x+w-12,y+6,5,15,'#97bdb2');break;
 case 'rug':rect(x,y,w,h,'#756b4c','#b5a672');text('2   0   4',x+w/2,y+18,'#d7caa0',13);break;
 case 'altar':circle(x+w/2,y+h/2,Math.min(w,h)/2-7,'#3d5140','#c9b77f');circle(x+w/2,y+h/2,25,'#3d5140','#b69e66');for(let i=0;i<3;i++){let a=i*2*Math.PI/3;circle(x+w/2+32*Math.cos(a),y+h/2+32*Math.sin(a),4,state.ritual?'#f2d77e':'#8f9677');}break;
 case 'terminal':rect(x+12,y+9,w-24,h-28,'#0e2c23','#a3b99b');text('TENANT_OS',x+w/2,y+31,'#9ee0af',11);text(state.exam+'/3',x+w/2,y+51,'#bfd59c',14);rect(x+14,y+h-15,w-28,7,'#879d7f');break;
 case 'tap':rect(x+5,y+6,w-10,h-12,'#adb9a5');circle(x+w/2,y+h/2,10,'#526c63');line(x+w/2,y+3,x+w/2,y+h/2,'#dce5ca',4);break;
 case 'runes':text('记忆 · 姓名 · 起源',x+w/2,y+h/2+4,'#ede0b2',11);break;
 case 'fuse':for(let i=0;i<3;i++)rect(x+8+i*16,y+12,9,22,'#bdbe9d','#3b5543');break;
 case 'door':line(x+8,y+h-5,x+w-8,y+h-5,'#d1bb84',2);circle(x+w-12,y+h/2,3,'#d3c18d');break;
 }
 ctx.restore();if(highlight){ctx.strokeStyle='#e4ce8c';ctx.lineWidth=2;ctx.setLineDash([4,3]);ctx.strokeRect(x-5,y-5,w+10,h+10);ctx.setLineDash([]);}text(o.name,x+w/2,y+h+17,highlight?'#f1dcaa':'#bbc5ac',11);
}
function draw(now,dt){const map=M.MAPS[state.floor];ctx.clearRect(0,0,1000,640);rect(0,0,1000,640,'#15251f');const tones=['#364c3e','#3b5148','#484e3b','#253e34'];for(const r of map.rooms){rect(r.x,r.y,r.w,r.h,tones[r.tone]);ctx.save();ctx.beginPath();ctx.rect(r.x,r.y,r.w,r.h);ctx.clip();ctx.globalAlpha=.13;for(let x=r.x;x<r.x+r.w;x+=32)line(x,r.y,x,r.y+r.h,'#c2c8a4');for(let y=r.y;y<r.y+r.h;y+=32)line(r.x,y,r.x+r.w,y,'#c2c8a4');ctx.restore();text(r.name,r.x+12,r.y+23,'#8d9d7e',12,'left');}
 // architectural wall fill and warm plan edges
 for(const [x,y,w,h]of map.walls){rect(x,y,w,h,'#b9b294','#ded4af');if(w>h)line(x,y+h+2,x+w,y+h+2,'#0c211a',2);else line(x+w+2,y,x+w+2,y+h,'#0c211a',2);}
 const near=M.nearby(state);map.objects.forEach(o=>drawObject(o,now,near));
 // Player: shadow, coat, shoulders and direction. Feet alternate while moving.
 const bob=moving?Math.sin(now*.018)*1.3:Math.sin(now*.002)*.5;ctx.save();ctx.translate(state.x,state.y);circle(1,5,13,'#05191180');ctx.rotate(state.facing);if(moving){rect(-7,-4,5,14+Math.sin(now*.024)*3,'#789c8d');rect(3,-4,5,14-Math.sin(now*.024)*3,'#789c8d');}ctx.fillStyle='#6db499';ctx.beginPath();ctx.ellipse(0,1,12,9,0,0,Math.PI*2);ctx.fill();circle(0,-3+bob,7,'#e2d9b6','#314d3e');ctx.restore();circle(state.x,state.y,19,'#0000','#8acbb366');ctx.beginPath();ctx.arc(state.x,state.y,24,state.facing-Math.PI*.7,state.facing-Math.PI*.3);ctx.strokeStyle='#cceec8';ctx.lineWidth=2;ctx.stroke();text('你',state.x,state.y+34,'#b9dec8',10);
 effects=effects.filter(f=>f.life>0);for(const f of effects){f.life-=dt*1.6;if(f.floor!==state.floor)continue;ctx.save();ctx.globalAlpha=Math.max(0,f.life);const col=f.type==='danger'?'#e8a38d':f.type==='water'?'#a5d1dc':'#e0cd88';ctx.strokeStyle=col;ctx.lineWidth=2;ctx.beginPath();ctx.arc(f.x,f.y,12+(1-f.life)*48,0,Math.PI*2);ctx.stroke();for(let i=0;i<5;i++){const a=i*Math.PI*.4;circle(f.x+Math.cos(a)*(1-f.life)*35,f.y+Math.sin(a)*(1-f.life)*35-12*(1-f.life),2,col);}ctx.restore();}
 if(state.floor==='basement'){const g=ctx.createRadialGradient(state.x,state.y,70,state.x,state.y,580);g.addColorStop(0,'#09161800');g.addColorStop(1,'#050d1690');ctx.fillStyle=g;ctx.fillRect(0,0,1000,640);}if(state.floor==='mirror'){ctx.fillStyle='#99d7c20b';ctx.fillRect(0,0,1000,640);}
 $('#interactionPrompt').textContent=state.ending?'本周目已结束':near?'E  '+near.name+'  ·  调查 / 操作':'W A S D / 方向键移动  ·  靠近物件按 E';
}
function frame(now){const dt=Math.min((now-last)/1000||0,.035);last=now;moving=false;if(overlay.hidden&&!state.ending){let dx=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),dy=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0);if(dx||dy){const norm=Math.hypot(dx,dy);dx/=norm;dy/=norm;state.facing=Math.atan2(dy,dx)+Math.PI/2;const x=state.x,y=state.y;M.move(state,dx*180*dt,dy*180*dt);moving=x!==state.x||y!==state.y;if(moving){step+=dt;if(step>.3){sound('step');step=0;}saveTimer+=dt;if(saveTimer>2){save();saveTimer=0;}}}}
 draw(now,dt);requestAnimationFrame(frame);}
window.addEventListener('keydown',e=>{const key=e.key.toLowerCase();if(e.ctrlKey||e.metaKey||e.altKey)return;if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright','e','j','escape'].includes(key))e.preventDefault();unlockAudio();if(!overlay.hidden){if(key==='escape'){if(state.ending)settlement();else closeDialog();}if(key==='tab'){const nodes=[...$('#dialog').querySelectorAll('button:not([disabled]):not([hidden])')];if(nodes.length){const i=nodes.indexOf(document.activeElement);if(e.shiftKey&&i<=0){e.preventDefault();nodes.at(-1).focus();}else if(!e.shiftKey&&i===nodes.length-1){e.preventDefault();nodes[0].focus();}}}return;}if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright'].includes(key))keys.add(key);if(!e.repeat&&key==='e')interact();if(!e.repeat&&key==='j')journal();});
window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{keys.clear();save();});document.addEventListener('visibilitychange',()=>{keys.clear();if(document.hidden)save();});window.addEventListener('pagehide',save);canvas.addEventListener('pointerdown',()=>{unlockAudio();canvas.focus();});
document.querySelectorAll('[data-move]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();unlockAudio();keys.add(b.dataset.move);b.setPointerCapture(e.pointerId);};b.onpointerup=b.onpointercancel=()=>keys.delete(b.dataset.move);});$('#interactTouch').onclick=interact;$('#closeDialog').onclick=()=>state.ending?settlement():closeDialog();$('#journal').onclick=journal;$('#collection').onclick=showCollection;$('#restart').onclick=confirmRestart;$('#sound').onclick=()=>{muted=!muted;unlockAudio();if(master)master.gain.value=muted?0:.15;$('#sound').textContent='声音：'+(muted?'关':'开');$('#sound').setAttribute('aria-pressed',String(muted));feedback('paper');};
renderHUD();save();requestAnimationFrame(frame);if(state.ending)settlement();else if(!loaded)openDialog('204 室，欢迎入住。','<p>平面图上的浅绿色小人是你。使用 <b>W A S D</b> 或方向键移动，靠近物件后按 <b>E</b> 调查，再选择具体操作。</p><p>先到玄关阅读守则。仓库的钥匙能通往阁楼与地下室；地下室只在深夜开放，必须按时返回。</p><p>移动和阅读不会走时。每次操作都会有声音与动画反馈，并自动保存。你可以服从、试探，或寻找规则背后的主人。</p>',[{label:'拿起钥匙，开始探索',run:()=>{feedback('door');closeDialog();}}],'NEW TENANT / 操作说明','intro');
// Read-only diagnostics for tests and inspection; no state mutation or teleport hooks.
window.tenantDebug={snapshot:()=>JSON.parse(JSON.stringify(state)),feedback:()=>({audioEvents,animations,audioState:ctxAudio?.state,muted}),nearby:()=>M.nearby(state)?.id||null};
})();
