const test=require('node:test');const assert=require('node:assert/strict');const T=require('../engine.js');const M=require('../maps.js');
function run(s,o,k){const r=T.execute(s,o,k);assert.equal(r.ok,true,`${o}/${k}: ${r.text}`);return r;}
function base(){const s=T.initial();run(s,'door','read');run(s,'cabinet','supplies');return s;}
function surface(s){run(s,'store','store');run(s,'bedroom3','diary');run(s,'up','up');run(s,'graffiti','runes');run(s,'back','back');run(s,'desk','origin');}
function tidy(s){run(s,'mirror','clean');run(s,'fridge','milk');run(s,'fridge','drink');run(s,'fridge','drink');run(s,'tray','bottle');run(s,'tray','meal');}
test('normal exit checks each prerequisite and preserves original 30-day threshold',()=>{const s=base();tidy(s);run(s,'desk','job');run(s,'bed','days7');assert.equal(s.cleanDays,7);run(s,'cabinet','return');run(s,'door','checkout');assert.equal(s.ending,null);run(s,'bed','days30');run(s,'clock','waitMorning');run(s,'door','checkout');assert.equal(s.ending,'safe');for(const id of ['qualified','model','silent','checkout'])assert.ok(s.achievements.includes(id));});
test('guardian requires 100 clean days and no exit attempt or historic violation',()=>{const s=base();tidy(s);run(s,'bed','days100');run(s,'bed','guardian');assert.equal(s.ending,'guardian');const bad=base();tidy(bad);run(bad,'door','checkout');run(bad,'bed','days100');run(bad,'bed','guardian');assert.equal(bad.ending,null);});
test('supply resources cannot be farmed, second milk pour reacts and fades',()=>{const s=base();run(s,'fridge','milk');assert.equal(T.execute(s,'fridge','milk').ok,false);run(s,'plant','pour');assert.equal(s.plantUntil,0);run(s,'plant','pour');assert.equal(s.milk,0);assert.ok(s.plantUntil>s.time);run(s,'plant','plantLook');assert.ok(s.achievements.includes('hidden'));assert.equal(T.execute(s,'plant','pour').ok,false);T.advance(s,30);assert.ok(s.plantUntil<=s.time);});
test('all floor transitions arrive on walkable ground',()=>{const s=base();run(s,'store','store');run(s,'up','up');assert.ok(M.canStand(s.floor,s.x,s.y),'attic spawn');run(s,'back','back');run(s,'clock','waitMidnight');run(s,'down','down');assert.ok(M.canStand(s.floor,s.x,s.y),'basement spawn');run(s,'back','back');assert.ok(M.canStand(s.floor,s.x,s.y),'safe spawn');});
test('basement is time-gated; crossing the deadline by a long wait or return causes lost ending',()=>{const s=base();run(s,'store','store');run(s,'down','down');assert.equal(s.floor,'safe');run(s,'clock','waitMidnight');run(s,'down','down');assert.equal(s.floor,'basement');T.advance(s,s.basementDeadline-s.time-1);run(s,'back','back');assert.equal(s.ending,'lost');const t=base();run(t,'store','store');run(t,'clock','waitMidnight');run(t,'down','down');T.advance(t,1440);assert.equal(t.ending,'lost');});
test('all ending branches are reachable through commands without injected flags',()=>{let s=base();surface(s);run(s,'clock','waitMidnight');run(s,'up','up');run(s,'altar','ritual');assert.equal(s.ritual,true);run(s,'altar','truth');assert.equal(s.ending,'truth');s=base();surface(s);run(s,'mirror','clean');run(s,'mirror','mirrorGate');assert.equal(s.floor,'mirror');run(s,'terminal','exam');run(s,'terminal','exam2');run(s,'terminal','exam3');assert.equal(s.ending,'admin');s=base();surface(s);run(s,'fridge','milk');run(s,'fridge','drink');run(s,'fridge','drink');run(s,'shoes','shoes');run(s,'clock','waitMidnight');run(s,'window','window');run(s,'clock','sync');assert.equal(s.ending,'breaker');assert.ok(s.achievements.includes('midnight'));s=base();run(s,'store','store');run(s,'fridge','milk');run(s,'mirror','clean');run(s,'mirror','reflection');run(s,'desk','ad');run(s,'door','handoff');assert.equal(s.ending,'relay');s=base();run(s,'store','store');run(s,'clock','waitMidnight');run(s,'down','down');run(s,'contract','sign');assert.equal(s.ending,'trap');s=base();for(let i=0;i<4;i++)run(s,'mirror','imitate');assert.equal(s.ending,'trapped');assert.equal(T.execute(s,'bed','rest').ok,false);});
test('five physical shortcuts, exploration and risk achievements work',()=>{const s=base();surface(s);run(s,'bedroom3','wallPass');run(s,'hatch','hatch');run(s,'rug','rugLook');run(s,'rug','hop');run(s,'clock','waitMidnight');run(s,'fridge','fridgeLook');run(s,'rug','rugPass');for(let i=0;i<10;i++)run(s,'fuse','eyes');run(s,'lift','lift');run(s,'mirror','clean');run(s,'mirror','mirrorGate');assert.equal(s.shortcuts.length,5);assert.ok(s.achievements.includes('shortcuts'));run(s,'mirrorBack','mirrorBack');run(s,'window','flash');run(s,'door','talk');for(const id of ['diary','cat','eyes','mirror','loophole','landlord'])assert.ok(s.achievements.includes(id),id);while(!s.ending)run(s,'mirror','imitate');assert.ok(s.achievements.includes('infinite'));});
test('no interaction through walls and every object is reachable from spawn',()=>{for(const [floor,map] of Object.entries(M.MAPS)){const q=[map.spawn],seen=new Set(),reach=new Set();while(q.length){const [x,y]=q.shift(),id=`${x}:${y}`;if(seen.has(id)||!M.canStand(floor,x,y))continue;seen.add(id);for(const o of map.objects)if(M.distance(x,y,o)<=55&&M.visible(floor,x,y,o))reach.add(o.id);for(const [dx,dy]of [[10,0],[-10,0],[0,10],[0,-10]])q.push([x+dx,y+dy]);}for(const o of map.objects)assert.ok(reach.has(o.id),`${floor}: unreachable ${o.id}`);}assert.equal(M.canStand('safe',390,200),false);const s=base();s.x=410;s.y=150;assert.ok(!M.nearby(s)||M.nearby(s).id!=='window');});
